# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    globals:
        enabledlangage: "%enabledlangage%"
    form:
        resources:
            - ::Form/fields.html.twig