services:
    zimzim_appbundle.form.type.zimzimcollectionformtype:
        class: AppBundle\Form\Type\ProductType
        tags:
            - { name: form.type, alias: appbundle_producttype }

    appbundle.form.type.contacttype:
        class: AppBundle\Form\Type\ContactType
        arguments: [ @security.context ]
        tags:
            - { name: form.type, alias: appbundle_contacttype }